import Foundation

struct Country: Identifiable, Hashable {
    let code: String // ISO 3166-1 alpha-2
    let name: String
    var id: String { code }
    var flagEmoji: String { code.toFlagEmoji() }

    // Popular destinations for the Explore screen
    static let popular: [Country] = [
        Country(code: "US", name: "United States"),
        Country(code: "GB", name: "United Kingdom"),
        Country(code: "FR", name: "France"),
        Country(code: "DE", name: "Germany"),
        Country(code: "IT", name: "Italy"),
        Country(code: "ES", name: "Spain"),
        Country(code: "JP", name: "Japan"),
        Country(code: "KR", name: "South Korea"),
        Country(code: "TH", name: "Thailand"),
        Country(code: "SG", name: "Singapore"),
        Country(code: "AU", name: "Australia"),
        Country(code: "CA", name: "Canada"),
        Country(code: "MX", name: "Mexico"),
        Country(code: "BR", name: "Brazil"),
        Country(code: "AR", name: "Argentina"),
        Country(code: "TR", name: "Turkey"),
        Country(code: "AE", name: "UAE"),
        Country(code: "SA", name: "Saudi Arabia"),
        Country(code: "EG", name: "Egypt"),
        Country(code: "MA", name: "Morocco"),
        Country(code: "NG", name: "Nigeria"),
        Country(code: "ZA", name: "South Africa"),
        Country(code: "IN", name: "India"),
        Country(code: "PK", name: "Pakistan"),
        Country(code: "BD", name: "Bangladesh"),
        Country(code: "CN", name: "China"),
        Country(code: "HK", name: "Hong Kong"),
        Country(code: "TW", name: "Taiwan"),
        Country(code: "ID", name: "Indonesia"),
        Country(code: "MY", name: "Malaysia"),
        Country(code: "PH", name: "Philippines"),
        Country(code: "VN", name: "Vietnam"),
        Country(code: "NZ", name: "New Zealand"),
        Country(code: "GR", name: "Greece"),
        Country(code: "PT", name: "Portugal"),
        Country(code: "NL", name: "Netherlands"),
        Country(code: "BE", name: "Belgium"),
        Country(code: "CH", name: "Switzerland"),
        Country(code: "AT", name: "Austria"),
        Country(code: "SE", name: "Sweden"),
        Country(code: "NO", name: "Norway"),
        Country(code: "DK", name: "Denmark"),
        Country(code: "FI", name: "Finland"),
        Country(code: "PL", name: "Poland"),
        Country(code: "CZ", name: "Czech Republic"),
        Country(code: "HU", name: "Hungary"),
        Country(code: "RO", name: "Romania"),
        Country(code: "HR", name: "Croatia"),
        Country(code: "RS", name: "Serbia"),
        Country(code: "BG", name: "Bulgaria"),
        Country(code: "GE", name: "Georgia"),
        Country(code: "AM", name: "Armenia"),
        Country(code: "IL", name: "Israel"),
        Country(code: "JO", name: "Jordan"),
        Country(code: "LB", name: "Lebanon"),
        Country(code: "KE", name: "Kenya"),
        Country(code: "GH", name: "Ghana"),
        Country(code: "TZ", name: "Tanzania"),
        Country(code: "ET", name: "Ethiopia"),
        Country(code: "CO", name: "Colombia"),
        Country(code: "CL", name: "Chile"),
        Country(code: "PE", name: "Peru"),
        Country(code: "EC", name: "Ecuador"),
        Country(code: "UY", name: "Uruguay"),
        Country(code: "PA", name: "Panama"),
        Country(code: "CR", name: "Costa Rica"),
        Country(code: "DO", name: "Dominican Republic"),
        Country(code: "CU", name: "Cuba"),
        Country(code: "JM", name: "Jamaica"),
        Country(code: "TT", name: "Trinidad & Tobago"),
        Country(code: "IS", name: "Iceland"),
        Country(code: "MT", name: "Malta"),
        Country(code: "CY", name: "Cyprus"),
        Country(code: "LU", name: "Luxembourg"),
        Country(code: "SK", name: "Slovakia"),
        Country(code: "SI", name: "Slovenia"),
        Country(code: "LT", name: "Lithuania"),
        Country(code: "LV", name: "Latvia"),
        Country(code: "EE", name: "Estonia"),
    ]
}
