import UIKit
import VeralifyCore

/// Draws the plan onto paper.
///
/// Hand-drawn rather than rendered from a SwiftUI view: the schedule runs
/// longer than one page, so the document has to control its own pagination, and
/// a drawn page is text a reader can select rather than a picture of text.
final class PlanPDF {
    let plan: PayoffPlan
    let steps: [JourneyStep]
    let summary: JourneySummary
    let style: PlanPDFStyle
    let accent: PlanPDFAccent

    /// Counted here rather than threaded through every layout's own loop.
    private var pageNumber = 0

    init(
        plan: PayoffPlan,
        steps: [JourneyStep],
        summary: JourneySummary,
        style: PlanPDFStyle,
        accent: PlanPDFAccent
    ) {
        self.plan = plan
        self.steps = steps
        self.summary = summary
        self.style = style
        self.accent = accent
    }

    static let pageSize = CGRect(x: 0, y: 0, width: 595, height: 842)

    let margin: CGFloat = 40
    var page: CGRect { Self.pageSize }
    var usable: CGFloat { page.width - margin * 2 }
    /// Room kept clear at the foot of every page for the signature line.
    var footerSpace: CGFloat { 54 }
    var ink: UIColor { accent.colour }

    // Fixed greys, not `.label` and friends. Those are dynamic: drawn from an
    // app running in dark mode they resolve to white, and the whole document
    // comes out blank on its white page. A print document has no business
    // following the screen's appearance.
    let primaryInk = UIColor(white: 0.11, alpha: 1)
    let secondaryInk = UIColor(white: 0.44, alpha: 1)
    let tertiaryInk = UIColor(white: 0.62, alpha: 1)

    // MARK: - Entry point

    func data() -> Data {
        pageNumber = 0
        return UIGraphicsPDFRenderer(bounds: page).pdfData { context in
            startPage(context)
            var y = drawMasthead(at: margin)
            if !style.isAnalytical { y = drawStats(at: y) }

            switch style {
            case .tracker:   drawTracker(from: y, context: context)
            case .plain:     drawPlain(from: y, context: context)
            case .cards:     drawCards(from: y, context: context)
            case .dashboard: drawDashboard(from: y, context: context)
            case .report:    drawReport(from: y, context: context)
            case .timeline:  drawTimeline(from: y, context: context)
            case .charts:    drawCharts(from: y, context: context)
            case .ledger:    drawLedger(from: y, context: context)
            case .calendar:  drawCalendar(from: y, context: context)
            case .statement: drawStatement(from: y, context: context)
            }
        }
    }

    /// Starts a page and signs it. Every page carries the mark, because a
    /// printed schedule gets separated from its first sheet.
    func startPage(_ context: UIGraphicsPDFRendererContext) {
        context.beginPage()
        pageNumber += 1
        drawFooter()
    }

    private func drawFooter() {
        let baseline = page.height - 34
        rule(y: baseline - 10)

        var x = margin
        if let mark = Self.logo {
            mark.draw(in: CGRect(x: x, y: baseline - 2, width: 11, height: 11))
            x += 15
        }

        text(
            String(localized: "Generated by Veralify"),
            at: CGPoint(x: x, y: baseline),
            font: .systemFont(ofSize: 7.5, weight: .semibold),
            colour: secondaryInk
        )

        text(
            Date().formatted(.dateTime.day().month(.abbreviated).year()),
            in: CGRect(x: page.width / 2 - 60, y: baseline, width: 120, height: 12),
            font: .systemFont(ofSize: 7.5),
            colour: tertiaryInk,
            alignment: .center
        )

        text(
            String(localized: "Page \(pageNumber)"),
            in: CGRect(x: page.width - margin - 80, y: baseline, width: 80, height: 12),
            font: .systemFont(ofSize: 7.5),
            colour: tertiaryInk,
            alignment: .right
        )
    }

    /// The app mark. Loaded once — a 1024px image decoded per page would
    /// dominate the cost of rendering the whole document.
    private static let logo = UIImage(named: "VeralifyLogo")

    // MARK: - Shared top

    private func drawMasthead(at y: CGFloat) -> CGFloat {
        if let mark = Self.logo {
            let size: CGFloat = 34
            mark.draw(in: CGRect(x: page.width - margin - size, y: y - 2, width: size, height: size))

            text(
                String(localized: "VERALIFY"),
                in: CGRect(x: page.width - margin - 140, y: y + 36, width: 140, height: 12),
                font: .systemFont(ofSize: 7, weight: .heavy),
                colour: tertiaryInk,
                alignment: .right
            )
        }

        text(
            String(localized: "Debt Payoff & Savings Plan"),
            at: CGPoint(x: margin, y: y),
            font: .systemFont(ofSize: 21, weight: .heavy)
        )

        let span = steps.isEmpty
            ? ""
            : " (\(JourneyStep.title(for: steps[0].month)) – \(JourneyStep.title(for: steps[steps.count - 1].month)))"
        text(
            String(localized: "\(steps.count)-month repayment schedule\(span)"),
            at: CGPoint(x: margin, y: y + 26),
            font: .systemFont(ofSize: 9),
            colour: secondaryInk
        )
        return y + 50
    }

    /// The four figures that decide whether the plan is worth following.
    func drawStats(at y: CGFloat) -> CGFloat {
        let facts: [(String, String, String)] = [
            (String(localized: "INITIAL PRINCIPAL"), CurrencyFormat.string(plan.totalDebt),
             String(localized: "Starting balance")),
            (String(localized: "TOTAL INTEREST"), CurrencyFormat.string(summary.totalInterest),
             String(localized: "Cost of borrowing")),
            (String(localized: "MONTHLY"), CurrencyFormat.string(plan.requiredMonthly),
             String(localized: "Fixed instalment")),
            (String(localized: "IN HAND AT THE END"),
             CurrencyFormat.string(steps.last?.cumulativeBalance ?? 0),
             String(localized: "Cash you keep"))
        ]

        let gap: CGFloat = 9
        let width = (usable - gap * CGFloat(facts.count - 1)) / CGFloat(facts.count)

        for (index, fact) in facts.enumerated() {
            let box = CGRect(x: margin + (width + gap) * CGFloat(index), y: y, width: width, height: 58)
            // The last one is what the plan is for, so it is the one picked out.
            let isFinal = index == facts.count - 1
            panel(box, fill: isFinal ? accent.wash : nil)

            text(fact.0, at: CGPoint(x: box.minX + 9, y: box.minY + 9),
                 font: .systemFont(ofSize: 6.5, weight: .bold), colour: secondaryInk)
            text(fact.1, at: CGPoint(x: box.minX + 9, y: box.minY + 20),
                 font: .systemFont(ofSize: 13, weight: .bold), colour: isFinal ? ink : primaryInk)
            text(fact.2, at: CGPoint(x: box.minX + 9, y: box.minY + 40),
                 font: .systemFont(ofSize: 6.5), colour: secondaryInk)
        }
        return y + 58 + 22
    }

    // MARK: - Tracker

    private var trackerColumns: [(title: String, width: CGFloat)] {
        [
            ("", 20),
            (String(localized: "PERIOD"), 50),
            (String(localized: "PAYMENT"), 56),
            (String(localized: "INTEREST"), 46),
            (String(localized: "PRINCIPAL"), 54),
            (String(localized: "REMAINING"), 60),
            (String(localized: "IN HAND"), 58),
            (String(localized: "PROGRESS"), 60),
            (String(localized: "MILESTONE"), 62)
        ]
    }

    private func drawTracker(from top: CGFloat, context: UIGraphicsPDFRendererContext) {
        text(String(localized: "MONTHLY SCHEDULE"), at: CGPoint(x: margin, y: top),
             font: .systemFont(ofSize: 9, weight: .bold))
        text(String(localized: "Tick each row as it is paid"),
             at: CGPoint(x: margin + 130, y: top + 1),
             font: .systemFont(ofSize: 7.5), colour: secondaryInk)

        var y = top + 18
        y = drawTrackerHeader(at: y)

        var previous = plan.totalDebt
        for step in steps {
            if y + 24 > page.height - footerSpace - 70 {
                startPage(context)
                y = margin
                y = drawTrackerHeader(at: y)
            }
            drawTrackerRow(step, previous: previous, at: y)
            previous = step.remainingDebt
            y += 24
        }

        // Measured against the footer, not the bare margin: the panels are
        // 104 tall below a 16 gap, and the old test let them run 14pt into the
        // signature line. `startPage` rather than `beginPage`, so the overflow
        // page is signed and numbered like every other.
        if y + 16 + 104 > page.height - footerSpace {
            startPage(context)
            y = margin
        }
        drawChecklists(at: y + 16)
    }

    private func drawTrackerHeader(at y: CGFloat) -> CGFloat {
        let bar = CGRect(x: margin, y: y, width: usable, height: 24)
        UIBezierPath(roundedRect: bar, cornerRadius: 4).addClip()
        ink.setFill()
        UIRectFill(bar)
        UIGraphicsGetCurrentContext()?.resetClip()

        var x = margin + 6
        for column in trackerColumns {
            text(column.title, in: CGRect(x: x, y: y + 8, width: column.width - 4, height: 12),
                 font: .systemFont(ofSize: 6.5, weight: .bold), colour: .white)
            x += column.width
        }
        return y + 28
    }

    private func drawTrackerRow(_ step: JourneyStep, previous: Decimal, at y: CGFloat) {
        if !step.index.isMultiple(of: 2) {
            UIColor(white: 0.97, alpha: 1).setFill()
            UIRectFill(CGRect(x: margin, y: y - 3, width: usable, height: 23))
        }

        var x = margin + 6
        checkbox(at: CGPoint(x: x, y: y + 2))
        x += trackerColumns[0].width

        let values = [
            step.month,
            CurrencyFormat.string(step.payment),
            CurrencyFormat.string(step.interest),
            CurrencyFormat.string(previous - step.remainingDebt),
            CurrencyFormat.string(step.isFinish ? 0 : step.remainingDebt),
            CurrencyFormat.string(step.cumulativeBalance)
        ]

        for (value, column) in zip(values, trackerColumns.dropFirst()) {
            text(value, in: CGRect(x: x, y: y + 4, width: column.width - 4, height: 14),
                 font: .monospacedDigitSystemFont(ofSize: 7.5, weight: step.isMilestone ? .bold : .regular))
            x += column.width
        }

        progressBar(
            at: CGRect(x: x, y: y + 8, width: trackerColumns[7].width - 20, height: 4),
            fraction: step.progress
        )
        text("\(Int((step.progress * 100).rounded()))%",
             at: CGPoint(x: x + trackerColumns[7].width - 18, y: y + 4),
             font: .monospacedDigitSystemFont(ofSize: 7, weight: .semibold), colour: secondaryInk)
        x += trackerColumns[7].width

        if step.isFinish {
            badge(String(localized: "Debt free"), at: CGPoint(x: x, y: y + 1), width: trackerColumns[8].width - 4)
        } else if let name = step.clearedDebts.first {
            badge(name, at: CGPoint(x: x, y: y + 1), width: trackerColumns[8].width - 4)
        } else {
            text("—", at: CGPoint(x: x + 4, y: y + 4), font: .systemFont(ofSize: 7.5), colour: tertiaryInk)
        }
    }

    /// The two lists worth ticking off away from the month grid: when each
    /// lender is finished with, and what the cash adds up to.
    private func drawChecklists(at y: CGFloat) {
        let gap: CGFloat = 12
        let width = (usable - gap) / 2
        let height: CGFloat = 104

        let left = CGRect(x: margin, y: y, width: width, height: height)
        panel(left, fill: nil)
        text(String(localized: "SETTLEMENT TARGETS"), at: CGPoint(x: left.minX + 10, y: left.minY + 10),
             font: .systemFont(ofSize: 7.5, weight: .bold))

        var row = left.minY + 28
        for debt in summary.perDebt.prefix(4) {
            checkbox(at: CGPoint(x: left.minX + 10, y: row))
            // Bounded so a long name stops short of the date beside it.
            text(debt.name, in: CGRect(x: left.minX + 26, y: row + 1, width: left.width - 26 - 114, height: 12),
                 font: .systemFont(ofSize: 8))
            let when = debt.clearedMonth.map { JourneyStep.title(for: $0) } ?? String(localized: "Not in this plan")
            text(when, in: CGRect(x: left.maxX - 110, y: row + 1, width: 100, height: 12),
                 font: .systemFont(ofSize: 8, weight: .semibold), alignment: .right)
            row += 18
        }

        let right = CGRect(x: margin + width + gap, y: y, width: width, height: height)
        panel(right, fill: accent.wash)
        text(String(localized: "WHAT YOU KEEP"), at: CGPoint(x: right.minX + 10, y: right.minY + 10),
             font: .systemFont(ofSize: 7.5, weight: .bold))

        let spare = plan.monthlyIncome - plan.monthlyExpenses - plan.requiredMonthly
        let facts: [(String, String)] = [
            (String(localized: "Spare each month"), CurrencyFormat.string(spare)),
            (String(localized: "In hand at the finish"), CurrencyFormat.string(steps.last?.cumulativeBalance ?? 0)),
            (String(localized: "Total interest paid"), CurrencyFormat.string(summary.totalInterest)),
            (String(localized: "Months to clear"), "\(steps.count)")
        ]

        row = right.minY + 28
        for fact in facts {
            text(fact.0, at: CGPoint(x: right.minX + 10, y: row + 1), font: .systemFont(ofSize: 8))
            text(fact.1, in: CGRect(x: right.maxX - 110, y: row + 1, width: 100, height: 12),
                 font: .systemFont(ofSize: 8, weight: .bold), colour: ink, alignment: .right)
            row += 18
        }
    }

    // MARK: - Plain

    private var plainColumns: [(title: String, width: CGFloat)] {
        [
            (String(localized: "Month"), 56), (String(localized: "Payment"), 62),
            (String(localized: "Interest"), 52), (String(localized: "Still owed"), 66),
            (String(localized: "Paid off"), 62), (String(localized: "In hand"), 62),
            (String(localized: "%"), 28)
        ]
    }

    private func drawPlain(from top: CGFloat, context: UIGraphicsPDFRendererContext) {
        var y = drawPlainHeader(at: top)
        var previous = plan.totalDebt

        for step in steps {
            if y + 22 > page.height - footerSpace {
                startPage(context)
                y = drawPlainHeader(at: margin)
            }

            var x = margin
            let values = [
                step.month,
                CurrencyFormat.string(step.payment),
                CurrencyFormat.string(step.interest),
                CurrencyFormat.string(step.isFinish ? 0 : step.remainingDebt),
                CurrencyFormat.string(previous - step.remainingDebt),
                CurrencyFormat.string(step.cumulativeBalance),
                "\(Int((step.progress * 100).rounded()))"
            ]
            for (value, column) in zip(values, plainColumns) {
                text(value, in: CGRect(x: x, y: y, width: column.width - 4, height: 16),
                     font: .monospacedDigitSystemFont(ofSize: 9, weight: step.isMilestone ? .semibold : .regular))
                x += column.width
            }

            if !step.clearedDebts.isEmpty {
                let note = step.clearedDebts.joined(separator: ", ") + " " + String(localized: "paid off")
                // Ends at the margin, where the rules and the footer end, not
                // 16pt from the paper's edge.
                text(note, in: CGRect(x: x + 6, y: y + 1, width: page.width - margin - x - 6, height: 14),
                     font: .systemFont(ofSize: 8, weight: .semibold), colour: ink)
            }

            previous = step.remainingDebt
            y += 22
        }
    }

    private func drawPlainHeader(at y: CGFloat) -> CGFloat {
        var x = margin
        for column in plainColumns {
            text(column.title, in: CGRect(x: x, y: y, width: column.width, height: 14),
                 font: .systemFont(ofSize: 8, weight: .semibold), colour: secondaryInk)
            x += column.width
        }
        rule(y: y + 16)
        return y + 22
    }

    // MARK: - Cards

    private func drawCards(from top: CGFloat, context: UIGraphicsPDFRendererContext) {
        let gap: CGFloat = 10
        let width = (usable - gap) / 2
        // Tall enough for the badge to clear the second row of figures. At 92
        // the milestone cards drew "Gam3yaa" straight over "€2,146.25".
        let height: CGFloat = 106

        var y = top
        var column = 0
        var previous = plan.totalDebt

        for step in steps {
            if y + height > page.height - footerSpace {
                startPage(context)
                y = margin
                column = 0
            }

            let box = CGRect(x: margin + (width + gap) * CGFloat(column), y: y, width: width, height: height)
            drawCard(step, previous: previous, in: box)

            previous = step.remainingDebt
            column += 1
            if column == 2 {
                column = 0
                y += height + gap
            }
        }
    }

    private func drawCard(_ step: JourneyStep, previous: Decimal, in box: CGRect) {
        panel(box, fill: step.isMilestone ? accent.wash : nil)

        text(JourneyStep.title(for: step.month), at: CGPoint(x: box.minX + 10, y: box.minY + 9),
             font: .systemFont(ofSize: 10, weight: .bold))
        text(CurrencyFormat.string(step.payment),
             in: CGRect(x: box.maxX - 90, y: box.minY + 9, width: 80, height: 14),
             font: .monospacedDigitSystemFont(ofSize: 10, weight: .bold), alignment: .right)

        progressBar(
            at: CGRect(x: box.minX + 10, y: box.minY + 28, width: box.width - 20, height: 4),
            fraction: step.progress
        )

        let facts: [(String, String)] = [
            (String(localized: "Still owed"), CurrencyFormat.string(step.isFinish ? 0 : step.remainingDebt)),
            (String(localized: "Paid off"), CurrencyFormat.string(previous - step.remainingDebt)),
            (String(localized: "In hand"), CurrencyFormat.string(step.cumulativeBalance)),
            (String(localized: "Progress"), "\(Int((step.progress * 100).rounded()))%")
        ]

        for (index, fact) in facts.enumerated() {
            let x = box.minX + 10 + CGFloat(index % 2) * (box.width - 20) / 2
            let y = box.minY + 42 + CGFloat(index / 2) * 20
            text(fact.0, at: CGPoint(x: x, y: y), font: .systemFont(ofSize: 6.5), colour: secondaryInk)
            text(fact.1, at: CGPoint(x: x, y: y + 8),
                 font: .monospacedDigitSystemFont(ofSize: 8.5, weight: .semibold))
        }

        if let name = step.clearedDebts.first {
            badge(name, at: CGPoint(x: box.minX + 10, y: box.maxY - 22), width: box.width - 20)
        }
    }

    // MARK: - Charts

    /// A filled curve. Used for both of the plan's stories — what is still owed
    /// falling, and what is kept rising — so the two are drawn the same way and
    /// can be read against each other.
    func areaChart(
        in rect: CGRect,
        values: [Decimal],
        colour: UIColor,
        title: String,
        caption: String? = nil
    ) {
        text(title, at: CGPoint(x: rect.minX, y: rect.minY),
             font: .systemFont(ofSize: 8.5, weight: .bold))
        if let caption {
            text(caption, in: CGRect(x: rect.maxX - 140, y: rect.minY, width: 140, height: 12),
                 font: .monospacedDigitSystemFont(ofSize: 8.5, weight: .bold),
                 colour: colour, alignment: .right)
        }

        let plot = CGRect(x: rect.minX, y: rect.minY + 16, width: rect.width, height: rect.height - 30)
        guard values.count > 1, let peak = values.max().map({ max($0.chartValue, 1) }) else { return }

        // Baselined at zero rather than at the smallest value: a debt curve that
        // starts at its own minimum looks like it never gets anywhere.
        func point(_ index: Int) -> CGPoint {
            let x = plot.minX + plot.width * CGFloat(index) / CGFloat(values.count - 1)
            let y = plot.maxY - plot.height * CGFloat(values[index].chartValue / peak)
            return CGPoint(x: x, y: y)
        }

        let fill = UIBezierPath()
        fill.move(to: CGPoint(x: plot.minX, y: plot.maxY))
        for index in values.indices { fill.addLine(to: point(index)) }
        fill.addLine(to: CGPoint(x: plot.maxX, y: plot.maxY))
        fill.close()
        colour.withAlphaComponent(0.14).setFill()
        fill.fill()

        let line = UIBezierPath()
        line.move(to: point(0))
        for index in values.indices.dropFirst() { line.addLine(to: point(index)) }
        colour.setStroke()
        line.lineWidth = 1.4
        line.lineJoinStyle = .round
        line.stroke()

        gridline(from: CGPoint(x: plot.minX, y: plot.maxY), to: CGPoint(x: plot.maxX, y: plot.maxY))

        if let first = steps.first, let last = steps.last {
            text(JourneyStep.title(for: first.month), at: CGPoint(x: plot.minX, y: plot.maxY + 3),
                 font: .systemFont(ofSize: 6.5), colour: tertiaryInk)
            text(JourneyStep.title(for: last.month),
                 in: CGRect(x: plot.maxX - 90, y: plot.maxY + 3, width: 90, height: 10),
                 font: .systemFont(ofSize: 6.5), colour: tertiaryInk, alignment: .right)
        }
    }

    /// One bar per debt, split into what was borrowed and what the borrowing
    /// cost. The split is the point: the second number is the one to act on.
    func debtBars(in rect: CGRect, title: String) {
        text(title, at: CGPoint(x: rect.minX, y: rect.minY),
             font: .systemFont(ofSize: 8.5, weight: .bold))

        let height: CGFloat = 26
        // A height of zero means "as many as there are"; otherwise only the
        // rows that fit, so a dashboard short of room stops above the footer
        // instead of drawing through it.
        let fitting = rect.height > 0 ? max(0, Int((rect.height - 18) / height)) : summary.perDebt.count
        let rows = Array(summary.perDebt.prefix(fitting))
        guard !rows.isEmpty, let widest = rows.map(\.paid).max(), widest > 0 else { return }

        // The interest note is drawn after the end of each bar. At full width
        // the longest bar left it no room and it ran off the page, so the bars
        // are scaled to leave space for the widest note.
        let noteFont = UIFont.systemFont(ofSize: 6.5)
        let noteRoom = rows
            .filter { $0.interest > 0 }
            .map { interestNote($0.interest).size(withAttributes: [.font: noteFont]).width + 5 }
            .max() ?? 0
        let track = max(0, rect.width - noteRoom)

        for (index, debt) in rows.enumerated() {
            let y = rect.minY + 18 + CGFloat(index) * height

            text(debt.name, in: CGRect(x: rect.minX, y: y, width: rect.width - 96, height: 10),
                 font: .systemFont(ofSize: 7.5, weight: .semibold))
            text(CurrencyFormat.string(debt.paid),
                 in: CGRect(x: rect.maxX - 90, y: y, width: 90, height: 10),
                 font: .monospacedDigitSystemFont(ofSize: 7.5, weight: .bold), alignment: .right)

            let full = track * (debt.paid / widest).chartValue
            let interest = debt.paid > 0 ? full * (debt.interest / debt.paid).chartValue : 0
            let bar = CGRect(x: rect.minX, y: y + 12, width: full, height: 6)

            UIBezierPath(roundedRect: bar, cornerRadius: 3).addClip()
            ink.setFill()
            UIRectFill(bar)
            accent.secondary.setFill()
            UIRectFill(CGRect(x: bar.maxX - interest, y: bar.minY, width: interest, height: bar.height))
            UIGraphicsGetCurrentContext()?.resetClip()

            if debt.interest > 0 {
                text(interestNote(debt.interest),
                     at: CGPoint(x: rect.minX + full + 5, y: y + 11),
                     font: noteFont, colour: tertiaryInk)
            }
        }
    }

    private func interestNote(_ interest: Decimal) -> String {
        "\(CurrencyFormat.string(interest)) " + String(localized: "interest")
    }

    /// Principal against interest, as one ring. A share is the one thing a ring
    /// reads better than a bar.
    func interestRing(in rect: CGRect) {
        let centre = CGPoint(x: rect.midX, y: rect.midY)
        let radius = min(rect.width, rect.height) / 2 - 4
        let share = summary.interestShare

        func arc(from: Double, to: Double, colour: UIColor) {
            let path = UIBezierPath(
                arcCenter: centre,
                radius: radius - 7,
                startAngle: CGFloat(-.pi / 2 + from * 2 * .pi),
                endAngle: CGFloat(-.pi / 2 + to * 2 * .pi),
                clockwise: true
            )
            colour.setStroke()
            path.lineWidth = 14
            path.stroke()
        }

        arc(from: 0, to: 1, colour: ink)
        if share > 0 { arc(from: 0, to: share, colour: accent.secondary) }

        text("\(Int((share * 100).rounded()))%",
             in: CGRect(x: centre.x - 30, y: centre.y - 10, width: 60, height: 14),
             font: .systemFont(ofSize: 13, weight: .heavy), alignment: .center)
        text(String(localized: "interest"),
             in: CGRect(x: centre.x - 30, y: centre.y + 4, width: 60, height: 10),
             font: .systemFont(ofSize: 6.5), colour: secondaryInk, alignment: .center)
    }

    func legendRow(at point: CGPoint, items: [(String, UIColor)]) {
        var x = point.x
        for item in items {
            let swatch = UIBezierPath(roundedRect: CGRect(x: x, y: point.y + 3, width: 10, height: 4), cornerRadius: 2)
            item.1.setFill()
            swatch.fill()
            let font = UIFont.systemFont(ofSize: 6.5)
            text(item.0, at: CGPoint(x: x + 14, y: point.y), font: font, colour: secondaryInk)
            // Measured, not estimated from the character count: the estimate
            // ran short for wider scripts and drew the next swatch over the
            // end of the label.
            x += 14 + (item.0 as NSString).size(withAttributes: [.font: font]).width + 16
        }
    }

    private func gridline(from: CGPoint, to: CGPoint) {
        let path = UIBezierPath()
        path.move(to: from)
        path.addLine(to: to)
        UIColor(white: 0.85, alpha: 1).setStroke()
        path.lineWidth = 0.5
        path.stroke()
    }

    // MARK: - Drawing primitives

    func text(
        _ value: String,
        at point: CGPoint,
        font: UIFont,
        colour: UIColor? = nil
    ) {
        value.draw(at: point, withAttributes: [.font: font, .foregroundColor: colour ?? primaryInk])
    }

    func text(
        _ value: String,
        in rect: CGRect,
        font: UIFont,
        colour: UIColor? = nil,
        alignment: NSTextAlignment = .left
    ) {
        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = alignment
        paragraph.lineBreakMode = .byTruncatingTail
        value.draw(in: rect, withAttributes: [
            .font: font, .foregroundColor: colour ?? primaryInk, .paragraphStyle: paragraph
        ])
    }

    func panel(_ rect: CGRect, fill: UIColor?) {
        let path = UIBezierPath(roundedRect: rect, cornerRadius: 5)
        if let fill {
            fill.setFill()
            path.fill()
        }
        UIColor(white: 0.84, alpha: 1).setStroke()
        path.lineWidth = 0.6
        path.stroke()
    }

    func rule(y: CGFloat) {
        let path = UIBezierPath()
        path.move(to: CGPoint(x: margin, y: y))
        path.addLine(to: CGPoint(x: page.width - margin, y: y))
        UIColor(white: 0.8, alpha: 1).setStroke()
        path.lineWidth = 0.5
        path.stroke()
    }

    /// An empty square, for ticking with a pen.
    func checkbox(at point: CGPoint) {
        let path = UIBezierPath(roundedRect: CGRect(x: point.x, y: point.y, width: 10, height: 10), cornerRadius: 2)
        UIColor(white: 0.55, alpha: 1).setStroke()
        path.lineWidth = 0.8
        path.stroke()
    }

    func progressBar(at rect: CGRect, fraction: Double) {
        let track = UIBezierPath(roundedRect: rect, cornerRadius: rect.height / 2)
        UIColor(white: 0.88, alpha: 1).setFill()
        track.fill()

        let width = rect.width * min(max(fraction, 0), 1)
        guard width > 0.5 else { return }
        let fill = UIBezierPath(
            roundedRect: CGRect(x: rect.minX, y: rect.minY, width: width, height: rect.height),
            cornerRadius: rect.height / 2
        )
        ink.setFill()
        fill.fill()
    }

    func badge(_ title: String, at point: CGPoint, width: CGFloat) {
        let box = CGRect(x: point.x, y: point.y, width: width, height: 16)
        let path = UIBezierPath(roundedRect: box, cornerRadius: 3)
        accent.wash.setFill()
        path.fill()
        ink.setStroke()
        path.lineWidth = 0.5
        path.stroke()

        text(title, in: box.insetBy(dx: 4, dy: 3.5), font: .systemFont(ofSize: 6.5, weight: .bold),
             colour: ink, alignment: .center)
    }
}
