// @ts-nocheck
import type { SupabaseLike } from './types.ts';
const isoDaysAgo = (days: number) => { const d = new Date(); d.setDate(d.getDate() - days); return d.toISOString().slice(0, 10); };
async function many(q: unknown) { const r = await q; if (r?.error) throw new Error(r.error.message); return r?.data ?? []; }
async function one(q: unknown) { const r = await q; if (r?.error) throw new Error(r.error.message); return r?.data ?? null; }
export function trimContextToBudget(context: Record<string, unknown>, maxChars = 6000) { let copy = structuredClone(context); let json = JSON.stringify(copy); while (json.length > maxChars && Array.isArray(copy.nutrition_history) && copy.nutrition_history.length > 3) { copy.nutrition_history = copy.nutrition_history.slice(-Math.ceil(copy.nutrition_history.length * 0.7)); json = JSON.stringify(copy); } while (json.length > maxChars && Array.isArray(copy.recent_food_logs) && copy.recent_food_logs.length > 3) { copy.recent_food_logs = copy.recent_food_logs.slice(0, Math.floor(copy.recent_food_logs.length * 0.7)); json = JSON.stringify(copy); } return copy; }
export async function getUserProfile(supabase: SupabaseLike, userId: string) { return await one(supabase.from('profiles').select('id,display_name,timezone,locale').eq('id', userId).maybeSingle()); }
export async function getActiveGoal(supabase: SupabaseLike, userId: string) { const rows = await many(supabase.from('goals').select('id,title,type,status,target_value,unit,target_date,start_date').eq('user_id', userId).eq('status', 'active').limit(1)); return rows[0] ?? null; }
export async function getGoalTargets(supabase: SupabaseLike, goalId?: string | null) { if (!goalId) return []; return await many(supabase.from('goal_targets').select('metric,target_value,unit,period').eq('goal_id', goalId)); }
export async function getNutritionHistory(supabase: SupabaseLike, userId: string, days = 7) { return await many(supabase.from('daily_nutrition_summaries').select('date,calories,protein_g,carbs_g,fat_g,fiber_g,water_ml,meal_count').eq('user_id', userId).gte('date', isoDaysAgo(days)).order('date', { ascending: true }).limit(days)); }
export async function getWeightTrend(supabase: SupabaseLike, userId: string, days = 30) { const rows = await many(supabase.from('weight_entries').select('measured_at,weight_kg').eq('user_id', userId).gte('measured_at', isoDaysAgo(days)).order('measured_at', { ascending: true }).limit(50)); if (rows.length < 2) return { entries: rows, delta_kg: null }; return { entries: rows, delta_kg: Number((rows.at(-1).weight_kg - rows[0].weight_kg).toFixed(2)) }; }
export async function getRecentFoodLogs(supabase: SupabaseLike, userId: string, days = 7) { return await many(supabase.from('food_logs').select('id,logged_at,source,photo_path,notes').eq('user_id', userId).gte('logged_at', isoDaysAgo(days)).order('logged_at', { ascending: false }).limit(20)); }
export async function buildCoachContext(supabase: SupabaseLike, userId: string, days = 7, maxChars = 6000) { const profile = await getUserProfile(supabase, userId); const goal = await getActiveGoal(supabase, userId); const [targets, nutrition_history, weight_trend, recent_food_logs] = await Promise.all([getGoalTargets(supabase, goal?.id), getNutritionHistory(supabase, userId, days), getWeightTrend(supabase, userId, 30), getRecentFoodLogs(supabase, userId, days)]); return trimContextToBudget({ profile, goal, goal_targets: targets, nutrition_history, weight_trend, recent_food_logs }, maxChars); }
export async function buildInsightContext(supabase: SupabaseLike, userId: string, kind = 'nutrition') { const goal = await getActiveGoal(supabase, userId); return trimContextToBudget({ kind, goal, goal_targets: await getGoalTargets(supabase, goal?.id), nutrition_history: await getNutritionHistory(supabase, userId, 7), weight_trend: await getWeightTrend(supabase, userId, 30) }, 6000); }
