// @ts-nocheck
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.49.8';
import { loadModelPolicy } from './registry.ts';
import { OpenRouterClient } from './openrouter.ts';
import { routedChat, runStructured } from './router.ts';
import { FoodAnalysisSchema, CoachResponseSchema, InsightResponseSchema, RecommendationResponseSchema, parseStructured, responseFormat } from './schemas.ts';
import { auditSafetyBlock, completeAiRequest, createAiRequest } from './logging.ts';
import { enforceInputSafety, SAFETY_POLICY_VERSION, validateOutputSafety } from './safety.ts';
import { enforceDailyCostCeiling, enforceRateLimit } from './ratelimit.ts';
import { getOpenRouterTools, TOOL_SCHEMA_VERSION } from './tools.ts';
import { GatewayError, type AiMessage, type AiTaskType } from './types.ts';
import { buildAnalyzeFoodResponse } from './food-pipeline.ts';
import { buildCoachContext, buildInsightContext } from './context.ts';
import { runToolLoop } from './tool-loop.ts';
import { getOrCreateConversation, getRecentAiMessages, persistFeedback, persistFoodEstimate, persistRecommendations, saveAiMessage, upsertDailyInsight } from './persistence.ts';

const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type', 'Access-Control-Allow-Methods': 'POST, OPTIONS' };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
const sse = (body: unknown) => new Response(`data: ${JSON.stringify(body)}\n\ndata: [DONE]\n\n`, { status: 200, headers: { ...corsHeaders, 'Content-Type': 'text/event-stream', 'Cache-Control': 'no-cache' } });
const requestId = () => crypto.randomUUID();
const promptFiles = { food: { version: 'food-vision-analysis@2026-08', file: './prompts/food-vision-analysis.md' }, foodVerification: { version: 'food-verification@2026-08', file: './prompts/food-verification.md' }, chat: { version: 'ai-coach-system@2026-08', file: './prompts/ai-coach-system.md' }, insight: { version: 'nutrition-insight@2026-08', file: './prompts/nutrition-insight.md' }, progress: { version: 'progress-analysis@2026-08', file: './prompts/progress-analysis.md' }, recommendations: { version: 'recommendations@2026-08', file: './prompts/recommendations.md' } };
async function readPrompt(key: keyof typeof promptFiles) { return await Deno.readTextFile(new URL(promptFiles[key].file, import.meta.url)); }
function bearer(req: Request) { const h = req.headers.get('authorization') ?? ''; const [scheme, token] = h.split(' '); return scheme?.toLowerCase() === 'bearer' && token ? token : null; }
async function auth(req: Request) { const url = Deno.env.get('SUPABASE_URL'); const service = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'); if (!url || !service) throw new GatewayError('INTERNAL_ERROR', 'Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.', 500); const supabase = createClient(url, service, { auth: { persistSession: false, autoRefreshToken: false } }); const token = bearer(req); if (!token) throw new GatewayError('UNAUTHORIZED', 'Bearer token required.', 401); const { data, error } = await supabase.auth.getUser(token); if (error || !data.user?.id) throw new GatewayError('UNAUTHORIZED', 'Invalid bearer token.', 401); return { supabase, user: data.user, token }; }
function routeName(url: URL) { return url.pathname.split('/').filter(Boolean).pop(); }
async function baseStart(supabase, policy, userId: string, task: AiTaskType, id: string) { await enforceDailyCostCeiling(supabase, userId, policy); return await createAiRequest(supabase, { userId, task, requestId: id, modelRequested: `policy:${task}` }); }
function asChatMessages(rows: unknown[]): AiMessage[] { return rows.map((r: any) => ({ role: r.role, content: typeof r.content?.text === 'string' ? r.content.text : JSON.stringify(r.content) })).filter((m) => ['user','assistant','tool'].includes(m.role)); }

async function run(req: Request) {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders });
  if (req.method !== 'POST') return json({ error: { code: 'BAD_REQUEST', message: 'Method not allowed.' } }, 405);
  const { supabase, user } = await auth(req); const policy = await loadModelPolicy(); await enforceRateLimit(user.id, policy); const route = routeName(new URL(req.url)); const payload = await req.json().catch(() => { throw new GatewayError('BAD_REQUEST', 'Invalid JSON body.', 400); }); const id = requestId(); const client = new OpenRouterClient();

  if (route === 'feedback') { const row = await persistFeedback(supabase, { userId: user.id, aiRequestId: String(payload.ai_request_id ?? ''), rating: typeof payload.rating === 'number' ? payload.rating : null, feedback: typeof payload.feedback === 'string' ? payload.feedback : null }); return json({ request_id: id, result: row }); }

  if (route === 'analyze-food') { const prompt = await readPrompt('food'); const task: AiTaskType = 'food_image'; const aiRequestId = await baseStart(supabase, policy, user.id, task, id); const text = JSON.stringify({ image_ref: payload.image_ref, context: payload.context ?? {} }); const safety = await enforceInputSafety(text, (c) => auditSafetyBlock(supabase, user.id, id, c)); const messages: AiMessage[] = [{ role: 'system', content: prompt }, { role: 'user', content: `Analyze this stored user food image reference. Identify candidates and portions only. Input: ${text}` }]; let result = await runStructured(policy, client, { task, userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles.food.version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages, responseFormat: responseFormat(FoodAnalysisSchema) }, (raw) => parseStructured(FoodAnalysisSchema, raw)); const foodPolicy = policy.food_pipeline ?? { verification_confidence_below: 0.82 }; if (result.parsed.overall_confidence < foodPolicy.verification_confidence_below || result.parsed.verification_recommended) { const verificationPrompt = await readPrompt('foodVerification'); const verification = await runStructured(policy, client, { task: 'food_verification', userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles.foodVerification.version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages: [{ role: 'system', content: verificationPrompt }, { role: 'user', content: `Verify/correct this result. Input: ${text}. Candidate result: ${JSON.stringify(result.parsed)}` }], responseFormat: responseFormat(FoodAnalysisSchema) }, (raw) => parseStructured(FoodAnalysisSchema, raw)); result = { ...verification, fallbackUsed: result.fallbackUsed || verification.fallbackUsed }; } validateOutputSafety(JSON.stringify(result.parsed)); const contract = await buildAnalyzeFoodResponse(supabase, policy, result.parsed); await persistFoodEstimate(supabase, { userId: user.id, imagePath: String(payload.image_ref ?? ''), model: result.model, result: { ai_request_id: aiRequestId, ...contract }, confidence: contract.overall_confidence, verified: !contract.items.some((i) => i.needs_verification) }); await completeAiRequest(supabase, aiRequestId, 'succeeded', result.model, result.fallbackUsed); return json({ request_id: id, ai_request_id: aiRequestId, model_policy_version: policy.model_policy_version, safety_policy_version: SAFETY_POLICY_VERSION, result: contract, safety }); }

  if (route === 'chat') { const prompt = await readPrompt('chat'); const userMessage = String(payload.message ?? ''); const advanced = payload.mode === 'advanced' || userMessage.length > 500; const task: AiTaskType = advanced ? 'advanced_chat' : 'simple_chat'; const aiRequestId = await baseStart(supabase, policy, user.id, task, id); const safety = await enforceInputSafety(userMessage, (c) => auditSafetyBlock(supabase, user.id, id, c)); const conversation = await getOrCreateConversation(supabase, user.id, payload.conversation_id, 'coach'); await saveAiMessage(supabase, { conversationId: conversation.id, role: 'user', content: { text: userMessage, request_id: id } }); const [context, historyRows] = await Promise.all([buildCoachContext(supabase, user.id, Number(payload.days ?? 7)), getRecentAiMessages(supabase, conversation.id, 12)]); const messages: AiMessage[] = [{ role: 'system', content: prompt }, { role: 'system', content: `Minimum required caller context only: ${JSON.stringify(context)}` }, ...asChatMessages(historyRows), { role: 'user', content: userMessage }]; const toolNames = ['get_user_profile','get_goal','get_today_nutrition','get_weight_trend','get_recent_food_logs','search_foods']; const toolProbe = await routedChat(policy, client, { task, userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles.chat.version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages, tools: getOpenRouterTools(toolNames) }); const loop = await runToolLoop({ rawMessage: toolProbe.raw, messages, supabase, userId: user.id, requestId: id, aiRequestId }); const result = await runStructured(policy, client, { task, userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles.chat.version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages: loop.messages, responseFormat: responseFormat(CoachResponseSchema), tools: getOpenRouterTools(toolNames) }, (raw) => parseStructured(CoachResponseSchema, raw)); result.fallbackUsed = result.fallbackUsed || toolProbe.fallbackUsed; validateOutputSafety(result.parsed.message); await saveAiMessage(supabase, { conversationId: conversation.id, role: 'assistant', content: result.parsed, model: result.model }); await completeAiRequest(supabase, aiRequestId, 'succeeded', result.model, result.fallbackUsed); const body = { request_id: id, ai_request_id: aiRequestId, conversation_id: conversation.id, result: result.parsed, safety }; return payload.stream ? sse(body) : json(body); }

  if (route === 'insight') { const kind = payload.type === 'progress' ? 'progress' : 'nutrition'; const promptKey = kind === 'progress' ? 'progress' : 'insight'; const prompt = await readPrompt(promptKey); const task: AiTaskType = kind === 'progress' ? 'weekly_analysis' : 'insight'; const aiRequestId = await baseStart(supabase, policy, user.id, task, id); const context = await buildInsightContext(supabase, user.id, kind); await enforceInputSafety(JSON.stringify(context), (c) => auditSafetyBlock(supabase, user.id, id, c)); const result = await runStructured(policy, client, { task, userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles[promptKey].version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages: [{ role: 'system', content: prompt }, { role: 'user', content: `Use only this minimal context: ${JSON.stringify(context)}` }], responseFormat: responseFormat(InsightResponseSchema) }, (raw) => parseStructured(InsightResponseSchema, raw)); validateOutputSafety(result.parsed.body); const persisted = await upsertDailyInsight(supabase, { userId: user.id, type: kind, title: result.parsed.title, body: result.parsed.body, sourceData: { window: '7d', ...context }, model: result.model, validUntil: result.parsed.valid_until ?? null }); await completeAiRequest(supabase, aiRequestId, 'succeeded', result.model, result.fallbackUsed); return json({ request_id: id, ai_request_id: aiRequestId, result: result.parsed, persisted_insight: persisted.row, idempotent_reused: !persisted.created }); }

  if (route === 'recommendations') { const prompt = await readPrompt('recommendations'); const task: AiTaskType = 'recommendations'; const aiRequestId = await baseStart(supabase, policy, user.id, task, id); const candidates = JSON.stringify(payload.candidates ?? []); await enforceInputSafety(candidates, (c) => auditSafetyBlock(supabase, user.id, id, c)); const result = await runStructured(policy, client, { task, userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles.recommendations.version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages: [{ role: 'system', content: prompt }, { role: 'user', content: `Rank only these prefiltered candidates: ${candidates}` }], responseFormat: responseFormat(RecommendationResponseSchema) }, (raw) => parseStructured(RecommendationResponseSchema, raw)); const rows = await persistRecommendations(supabase, user.id, result.model, result.parsed.recommendations); await completeAiRequest(supabase, aiRequestId, 'succeeded', result.model, result.fallbackUsed); return json({ request_id: id, ai_request_id: aiRequestId, result: result.parsed, persisted_recommendations: rows }); }
  return json({ error: { code: 'BAD_REQUEST', message: 'Unknown ai-gateway route.' } }, 404);
}
Deno.serve(async (req) => { try { return await run(req); } catch (e) { if (e instanceof GatewayError) return json({ error: { code: e.code, message: e.message, details: e.details } }, e.status); console.error('ai-gateway internal error', e); return json({ error: { code: 'INTERNAL_ERROR', message: e instanceof Error ? e.message : 'Unexpected AI gateway error.' } }, 500); } });
