// @ts-nocheck
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.49.8';
import { loadModelPolicy } from './registry.ts';
import { OpenRouterClient } from './openrouter.ts';
import { runStructured, routedChat } from './router.ts';
import { FoodAnalysisSchema, CoachResponseSchema, InsightResponseSchema, RecommendationResponseSchema, parseStructured, responseFormat } from './schemas.ts';
import { auditSafetyBlock, completeAiRequest, createAiRequest } from './logging.ts';
import { enforceInputSafety, SAFETY_POLICY_VERSION, validateOutputSafety } from './safety.ts';
import { enforceDailyCostCeiling, enforceRateLimit } from './ratelimit.ts';
import { getOpenRouterTools, TOOL_SCHEMA_VERSION } from './tools.ts';
import { GatewayError, type AiMessage, type AiTaskType } from './types.ts';
const corsHeaders = { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type', 'Access-Control-Allow-Methods': 'POST, OPTIONS' };
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
const requestId = () => crypto.randomUUID();
const promptFiles = {
  food: { version: 'food-vision-analysis@2026-08', file: './prompts/food-vision-analysis.md' },
  chat: { version: 'ai-coach-system@2026-08', file: './prompts/ai-coach-system.md' },
  insight: { version: 'nutrition-insight@2026-08', file: './prompts/nutrition-insight.md' },
  progress: { version: 'progress-analysis@2026-08', file: './prompts/progress-analysis.md' },
  recommendations: { version: 'recommendations@2026-08', file: './prompts/recommendations.md' }
};
async function readPrompt(key: keyof typeof promptFiles) { return await Deno.readTextFile(new URL(promptFiles[key].file, import.meta.url)); }
function bearer(req: Request) { const h = req.headers.get('authorization') ?? ''; const [scheme, token] = h.split(' '); return scheme?.toLowerCase() === 'bearer' && token ? token : null; }
async function auth(req: Request) { const url = Deno.env.get('SUPABASE_URL'); const service = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'); if (!url || !service) throw new GatewayError('INTERNAL_ERROR', 'Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.', 500); const supabase = createClient(url, service, { auth: { persistSession: false, autoRefreshToken: false } }); const token = bearer(req); if (!token) throw new GatewayError('UNAUTHORIZED', 'Bearer token required.', 401); const { data, error } = await supabase.auth.getUser(token); if (error || !data.user?.id) throw new GatewayError('UNAUTHORIZED', 'Invalid bearer token.', 401); return { supabase, user: data.user }; }
function routeName(url: URL) { const last = url.pathname.split('/').filter(Boolean).pop(); return last; }
async function run(req: Request) { if (req.method === 'OPTIONS') return new Response('ok', { headers: corsHeaders }); if (req.method !== 'POST') return json({ error: { code: 'BAD_REQUEST', message: 'Method not allowed.' } }, 405); const { supabase, user } = await auth(req); const policy = await loadModelPolicy(); await enforceRateLimit(user.id, policy); const route = routeName(new URL(req.url)); const payload = await req.json().catch(() => { throw new GatewayError('BAD_REQUEST', 'Invalid JSON body.', 400); }); const id = requestId(); const client = new OpenRouterClient();
  const base = async (task: AiTaskType, modelRequested: string) => { await enforceDailyCostCeiling(supabase, user.id, policy); return await createAiRequest(supabase, { userId: user.id, task, requestId: id, modelRequested }); };
  if (route === 'analyze-food') { const prompt = await readPrompt('food'); const task: AiTaskType = 'food_image'; const aiRequestId = await base(task, 'policy:food_image'); const text = JSON.stringify({ image_ref: payload.image_ref, context: payload.context ?? {} }); const safety = await enforceInputSafety(text, (c) => auditSafetyBlock(supabase, user.id, id, c)); const messages: AiMessage[] = [{ role: 'system', content: prompt }, { role: 'user', content: `Analyze this stored user food image reference. Do not compute final nutrition. Input: ${text}` }]; const result = await runStructured(policy, client, { task, userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles.food.version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages, responseFormat: responseFormat(FoodAnalysisSchema) }, (raw) => parseStructured(FoodAnalysisSchema, raw)); validateOutputSafety(JSON.stringify(result.parsed)); await completeAiRequest(supabase, aiRequestId, 'succeeded', result.model, result.fallbackUsed); return json({ request_id: id, model_policy_version: policy.model_policy_version, safety_policy_version: SAFETY_POLICY_VERSION, result: result.parsed, safety }); }
  if (route === 'chat') { const prompt = await readPrompt('chat'); const userMessage = String(payload.message ?? ''); const advanced = payload.mode === 'advanced' || userMessage.length > 500; const task: AiTaskType = advanced ? 'advanced_chat' : 'simple_chat'; const aiRequestId = await base(task, `policy:${task}`); const safety = await enforceInputSafety(userMessage, (c) => auditSafetyBlock(supabase, user.id, id, c)); const history = Array.isArray(payload.messages) ? payload.messages.slice(-10) : []; const messages: AiMessage[] = [{ role: 'system', content: prompt }, ...history, { role: 'user', content: userMessage }]; const result = await runStructured(policy, client, { task, userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles.chat.version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages, responseFormat: responseFormat(CoachResponseSchema), tools: getOpenRouterTools() }, (raw) => parseStructured(CoachResponseSchema, raw)); validateOutputSafety(result.parsed.message); await completeAiRequest(supabase, aiRequestId, 'succeeded', result.model, result.fallbackUsed); return json({ request_id: id, result: result.parsed, safety }); }
  if (route === 'insight') { const kind = payload.type === 'progress' ? 'progress' : 'insight'; const prompt = await readPrompt(kind); const task: AiTaskType = kind === 'progress' ? 'weekly_analysis' : 'insight'; const aiRequestId = await base(task, `policy:${task}`); const minimalContext = JSON.stringify(payload.context ?? {}); await enforceInputSafety(minimalContext, (c) => auditSafetyBlock(supabase, user.id, id, c)); const result = await runStructured(policy, client, { task, userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles[kind].version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages: [{ role: 'system', content: prompt }, { role: 'user', content: `Use only this minimal context: ${minimalContext}` }], responseFormat: responseFormat(InsightResponseSchema) }, (raw) => parseStructured(InsightResponseSchema, raw)); validateOutputSafety(result.parsed.body); await completeAiRequest(supabase, aiRequestId, 'succeeded', result.model, result.fallbackUsed); return json({ request_id: id, result: result.parsed }); }
  if (route === 'recommendations') { const prompt = await readPrompt('recommendations'); const task: AiTaskType = 'recommendations'; const aiRequestId = await base(task, 'policy:recommendations'); const candidates = JSON.stringify(payload.candidates ?? []); await enforceInputSafety(candidates, (c) => auditSafetyBlock(supabase, user.id, id, c)); const result = await runStructured(policy, client, { task, userId: user.id, requestId: id, aiRequestId, promptVersion: promptFiles.recommendations.version, toolSchemaVersion: TOOL_SCHEMA_VERSION, safetyPolicyVersion: SAFETY_POLICY_VERSION, supabase, messages: [{ role: 'system', content: prompt }, { role: 'user', content: `Rank only these prefiltered candidates: ${candidates}` }], responseFormat: responseFormat(RecommendationResponseSchema) }, (raw) => parseStructured(RecommendationResponseSchema, raw)); await completeAiRequest(supabase, aiRequestId, 'succeeded', result.model, result.fallbackUsed); return json({ request_id: id, result: result.parsed }); }
  return json({ error: { code: 'BAD_REQUEST', message: 'Unknown ai-gateway route.' } }, 404);
}
Deno.serve(async (req) => { try { return await run(req); } catch (e) { if (e instanceof GatewayError) return json({ error: { code: e.code, message: e.message, details: e.details } }, e.status); console.error('ai-gateway internal error', e); return json({ error: { code: 'INTERNAL_ERROR', message: 'Unexpected AI gateway error.' } }, 500); } });
