// @ts-nocheck
import { GatewayError, type AiMessage, type ToolDefinition, type Usage } from './types.ts';
export type OpenRouterTransport = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export type ChatParams = { model: string; messages: AiMessage[]; maxTokens: number; timeoutMs: number; providerOrder?: string[]; responseFormat?: Record<string, unknown>; tools?: ToolDefinition[]; stream?: boolean; signal?: AbortSignal };
export type ChatResult = { content: string; model: string; provider: string | null; usage: Usage; raw: unknown };
export class OpenRouterError extends Error { constructor(message: string, public status: number, public retryable: boolean, public providerError = true) { super(message); } }
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms));
const jitter = (base: number) => base + Math.floor(Math.random() * base * 0.3);
export function requireOpenRouterApiKey(): string { const key = Deno.env.get('OPENROUTER_API_KEY'); if (!key) throw new GatewayError('MISSING_OPENROUTER_API_KEY', 'OPENROUTER_API_KEY is required for ai-gateway. Set it in Supabase function secrets.', 503); return key; }
export class OpenRouterClient { constructor(private apiKey = requireOpenRouterApiKey(), private transport: OpenRouterTransport = fetch) {}
  async chat(params: ChatParams): Promise<ChatResult> { let last: unknown; for (let attempt = 0; attempt <= 2; attempt++) { try { return await this.chatOnce(params); } catch (e) { last = e; const retryable = e instanceof OpenRouterError ? e.retryable : e instanceof DOMException && e.name === 'AbortError'; if (!retryable || attempt === 2) throw e; await sleep(jitter(150 * 2 ** attempt)); } } throw last; }
  private async chatOnce(params: ChatParams): Promise<ChatResult> { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), params.timeoutMs); params.signal?.addEventListener('abort', () => controller.abort(), { once: true }); const body: Record<string, unknown> = { model: params.model, messages: params.messages, max_tokens: params.maxTokens, stream: !!params.stream }; if (params.providerOrder?.length) body.provider = { order: params.providerOrder, allow_fallbacks: true }; if (params.responseFormat) body.response_format = params.responseFormat; if (params.tools?.length) body.tools = params.tools; try { const res = await this.transport('https://openrouter.ai/api/v1/chat/completions', { method: 'POST', headers: { Authorization: `Bearer ${this.apiKey}`, 'Content-Type': 'application/json', 'HTTP-Referer': 'https://veralify.com', 'X-Title': 'Veralify AI Gateway' }, body: JSON.stringify(body), signal: controller.signal }); if (!res.ok) { const text = await res.text().catch(() => ''); throw new OpenRouterError(text || `OpenRouter ${res.status}`, res.status, [408, 409, 425, 429, 500, 502, 503, 504].includes(res.status)); } if (params.stream) return await this.readStreaming(res); const data = await res.json(); const choice = Array.isArray(data?.choices) ? data.choices[0] : undefined; const content = typeof choice?.message?.content === 'string' ? choice.message.content : Array.isArray(choice?.message?.content) ? choice.message.content.map((p: Record<string, unknown>) => p.text ?? '').join('') : ''; return { content, model: String(data?.model ?? params.model), provider: typeof data?.provider === 'string' ? data.provider : null, usage: extractUsage(data?.usage), raw: data }; } catch (e) { if (e instanceof DOMException && e.name === 'AbortError') throw new OpenRouterError('OpenRouter request timed out', 408, true); throw e; } finally { clearTimeout(timeout); } }
  private async readStreaming(res: Response): Promise<ChatResult> { const reader = res.body?.getReader(); if (!reader) throw new OpenRouterError('Streaming response missing body', 502, true); const decoder = new TextDecoder(); let buf = '', content = '', model = ''; let usage: Usage = { inputTokens: 0, outputTokens: 0 }; while (true) { const { done, value } = await reader.read(); if (done) break; buf += decoder.decode(value, { stream: true }); const parts = buf.split('\n\n'); buf = parts.pop() ?? ''; for (const part of parts) { const line = part.split('\n').find((l) => l.startsWith('data: ')); if (!line) continue; const payload = line.slice(6).trim(); if (payload === '[DONE]') continue; const data = JSON.parse(payload); model = String(data.model ?? model); const delta = data.choices?.[0]?.delta?.content; if (typeof delta === 'string') content += delta; if (data.usage) usage = extractUsage(data.usage); } } return { content, model, provider: null, usage, raw: null }; }
}
export function extractUsage(u: unknown): Usage { const r = (u && typeof u === 'object') ? u as Record<string, unknown> : {}; const inputTokens = Number(r.prompt_tokens ?? r.input_tokens ?? 0); const outputTokens = Number(r.completion_tokens ?? r.output_tokens ?? 0); const reasoningRaw = r.reasoning_tokens; return { inputTokens: Number.isFinite(inputTokens) ? inputTokens : 0, outputTokens: Number.isFinite(outputTokens) ? outputTokens : 0, reasoningTokens: typeof reasoningRaw === 'number' ? reasoningRaw : null }; }
export function isProviderFallbackError(e: unknown): boolean { return e instanceof OpenRouterError && e.providerError && e.retryable; }
