// @ts-nocheck
import type { AiTaskType } from './types.ts';
export type RolePolicy = { display_name: string; primary_model: string; fallback_models: string[]; allowed_providers: string[]; provider_preferences: { order: string[]; allow_fallbacks: boolean }; max_cost_per_run_usd: number; latency_target_ms: number; timeout_ms: number; max_tokens: number };
export type TaskPolicy = { role: string; verification_role?: string; review_role?: string; ambiguous_role?: string; verification_confidence_below?: number };
export type ModelPolicy = { model_policy_version: string; benchmark_version: string; roles: Record<string, RolePolicy>; task_routing: Record<AiTaskType, TaskPolicy>; reference_pricing: Record<string, { input_per_million_usd: number; output_per_million_usd: number }>; limits: { per_user_per_minute: number; daily_cost_ceiling_usd: number }; food_pipeline?: { auto_accept_threshold: number; needs_user_confirm_threshold: number; reject_threshold: number; verification_confidence_below: number } };
export async function loadModelPolicy(path = new URL('./model-policy.json', import.meta.url)): Promise<ModelPolicy> { return validatePolicy(JSON.parse(await Deno.readTextFile(path))); }
export function validatePolicy(policy: ModelPolicy): ModelPolicy { if (!policy.model_policy_version || !policy.roles || !policy.task_routing) throw new Error('Invalid AI model policy'); for (const [roleName, role] of Object.entries(policy.roles)) { if (!role.primary_model || !Array.isArray(role.fallback_models)) throw new Error(`Invalid role policy: ${roleName}`); for (const model of [role.primary_model, ...role.fallback_models]) if (!policy.reference_pricing[model]) throw new Error(`Missing pricing for ${model}`); } return policy; }
export function getTaskPolicy(policy: ModelPolicy, task: AiTaskType) { const taskPolicy = policy.task_routing[task]; if (!taskPolicy) throw new Error(`No routing policy for task ${task}`); const rolePolicy = policy.roles[taskPolicy.role]; if (!rolePolicy) throw new Error(`No role policy ${taskPolicy.role}`); return { taskPolicy, rolePolicy, models: [rolePolicy.primary_model, ...rolePolicy.fallback_models] }; }
export function estimateCostUsd(policy: ModelPolicy, model: string, inputTokens = 0, outputTokens = 0): number { const p = policy.reference_pricing[model]; return p ? (inputTokens / 1_000_000) * p.input_per_million_usd + (outputTokens / 1_000_000) * p.output_per_million_usd : 0; }
