// @ts-nocheck
import { estimateCostUsd, getTaskPolicy, type ModelPolicy } from './registry.ts';
import { type ChatParams, type ChatResult, isProviderFallbackError, OpenRouterClient } from './openrouter.ts';
import { GatewayError, type AiTaskType, type SupabaseLike, type Usage } from './types.ts';
import { logModelRun } from './logging.ts';
export type RoutedChatParams = Omit<ChatParams, 'model' | 'timeoutMs' | 'maxTokens' | 'providerOrder'> & { task: AiTaskType; userId: string; requestId: string; aiRequestId?: string | null; promptVersion: string; toolSchemaVersion: string; safetyPolicyVersion: string; supabase: SupabaseLike };
export type RoutedChatResult = ChatResult & { requestedModel: string; fallbackUsed: boolean; estimatedCostUsd: number };
export function resolveModelsForTask(policy: ModelPolicy, task: AiTaskType) { return getTaskPolicy(policy, task); }
export async function routedChat(policy: ModelPolicy, client: OpenRouterClient, params: RoutedChatParams): Promise<RoutedChatResult> { const { rolePolicy, models } = getTaskPolicy(policy, params.task); const requestedModel = models[0]; let last: unknown; for (let i = 0; i < models.length; i++) { const model = models[i]; const start = performance.now(); let usage: Usage = { inputTokens: 0, outputTokens: 0, reasoningTokens: null }; try { const result = await client.chat({ ...params, model, timeoutMs: rolePolicy.timeout_ms, maxTokens: rolePolicy.max_tokens, providerOrder: rolePolicy.provider_preferences.order }); usage = result.usage; const cost = estimateCostUsd(policy, result.model || model, usage.inputTokens, usage.outputTokens); const overBudget = cost > rolePolicy.max_cost_per_run_usd; await logModelRun(params.supabase, { requestId: params.requestId, aiRequestId: params.aiRequestId, userId: params.userId, task: params.task, model: result.model || model, provider: result.provider, modelPolicyVersion: policy.model_policy_version, promptVersion: params.promptVersion, toolSchemaVersion: params.toolSchemaVersion, safetyPolicyVersion: params.safetyPolicyVersion, latencyMs: Math.round(performance.now() - start), estimatedCostUsd: cost, success: !overBudget, structuredOutputValid: true, usage }); if (overBudget) throw new GatewayError('MODEL_UNAVAILABLE', 'Model run exceeded configured per-run budget.', 502); return { ...result, requestedModel, fallbackUsed: i > 0, estimatedCostUsd: cost }; } catch (e) { last = e; await logModelRun(params.supabase, { requestId: params.requestId, aiRequestId: params.aiRequestId, userId: params.userId, task: params.task, model, provider: null, modelPolicyVersion: policy.model_policy_version, promptVersion: params.promptVersion, toolSchemaVersion: params.toolSchemaVersion, safetyPolicyVersion: params.safetyPolicyVersion, latencyMs: Math.round(performance.now() - start), estimatedCostUsd: estimateCostUsd(policy, model, usage.inputTokens, usage.outputTokens), success: false, structuredOutputValid: false, usage }); const canFallback = i < models.length - 1 && (isProviderFallbackError(e) || e instanceof GatewayError); if (!canFallback) throw e; } } throw last instanceof Error ? last : new GatewayError('MODEL_UNAVAILABLE', 'No model available', 502); }
export async function runStructured<T>(policy: ModelPolicy, client: OpenRouterClient, params: RoutedChatParams, parse: (raw: string) => T, repairInstruction = 'Return only valid JSON matching the provided schema.'): Promise<RoutedChatResult & { parsed: T }> { try { const first = await routedChat(policy, client, params); try { return { ...first, parsed: parse(first.content) }; } catch (e) { const repaired = await routedChat(policy, client, { ...params, messages: [...params.messages, { role: 'assistant', content: first.content }, { role: 'user', content: repairInstruction }] }); return { ...repaired, fallbackUsed: first.fallbackUsed || repaired.fallbackUsed, parsed: parse(repaired.content) }; } } catch (e) { if (e instanceof GatewayError) throw e; throw new GatewayError('STRUCTURED_OUTPUT_INVALID', e instanceof Error ? e.message : 'Structured output failed', 502); } }
