// @ts-nocheck
import { GatewayError } from './types.ts';
export type Schema<T> = { name: string; jsonSchema: Record<string, unknown>; parse(value: unknown): T };
const isObj = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v);
const num = (v: unknown, name: string, min = -Infinity, max = Infinity) => { if (typeof v !== 'number' || !Number.isFinite(v) || v < min || v > max) throw new Error(`${name} must be number`); return v; };
const str = (v: unknown, name: string) => { if (typeof v !== 'string' || !v.trim()) throw new Error(`${name} must be string`); return v; };
const bool = (v: unknown, name: string) => { if (typeof v !== 'boolean') throw new Error(`${name} must be boolean`); return v; };
const arr = <T>(v: unknown, name: string, f: (x: unknown, i: number) => T) => { if (!Array.isArray(v)) throw new Error(`${name} must be array`); return v.map(f); };
const strArr = (v: unknown, name: string) => arr(v ?? [], name, (x) => str(x, name));
export type FoodCandidate = { name: string; canonical_hint?: string; confidence: number; assumptions: string[] };
export type PortionEstimate = { food_name: string; quantity: number; unit: string; grams: number; confidence: number; assumptions: string[] };
export type FoodAnalysisResult = { items: Array<FoodCandidate & { portion: PortionEstimate }>; overall_confidence: number; requires_confirmation: boolean; verification_recommended: boolean };
export type CoachResponse = { message: string; safety_disclaimer?: string; suggested_actions: string[]; tool_results_used: string[]; confidence: number };
export type InsightResponse = { type: 'nutrition' | 'progress' | 'goal' | 'general'; title: string; body: string; supporting_facts: string[]; confidence: number; valid_until?: string | null };
export type RecommendationResponse = { recommendations: Array<{ recommendation_type: 'group' | 'live_room' | 'habit' | 'coach'; target_id?: string | null; title: string; reason: string; score: number }>; confidence: number };
const foodItem = (x: unknown, i: number): FoodAnalysisResult['items'][number] => { if (!isObj(x)) throw new Error(`items[${i}] object`); const p = x.portion; if (!isObj(p)) throw new Error(`items[${i}].portion object`); const name = str(x.name, `items[${i}].name`); return { name, canonical_hint: typeof x.canonical_hint === 'string' ? x.canonical_hint : undefined, confidence: num(x.confidence, 'confidence', 0, 1), assumptions: strArr(x.assumptions, 'assumptions'), portion: { food_name: str(p.food_name ?? name, 'food_name'), quantity: num(p.quantity, 'quantity', 0), unit: str(p.unit, 'unit'), grams: num(p.grams, 'grams', 0), confidence: num(p.confidence, 'portion.confidence', 0, 1), assumptions: strArr(p.assumptions, 'portion.assumptions') } }; };
export const FoodAnalysisSchema: Schema<FoodAnalysisResult> = { name: 'FoodAnalysisResult', jsonSchema: { type: 'object', additionalProperties: false, required: ['items','overall_confidence','requires_confirmation','verification_recommended'], properties: { items: { type: 'array', items: { type: 'object' } }, overall_confidence: { type: 'number', minimum: 0, maximum: 1 }, requires_confirmation: { type: 'boolean' }, verification_recommended: { type: 'boolean' } } }, parse(v) { if (!isObj(v)) throw new Error('FoodAnalysisResult object'); return { items: arr(v.items, 'items', foodItem), overall_confidence: num(v.overall_confidence, 'overall_confidence', 0, 1), requires_confirmation: bool(v.requires_confirmation, 'requires_confirmation'), verification_recommended: bool(v.verification_recommended, 'verification_recommended') }; } };
export const CoachResponseSchema: Schema<CoachResponse> = { name: 'CoachResponse', jsonSchema: { type: 'object', required: ['message','suggested_actions','tool_results_used','confidence'], properties: { message: { type: 'string' }, safety_disclaimer: { type: 'string' }, suggested_actions: { type: 'array', items: { type: 'string' } }, tool_results_used: { type: 'array', items: { type: 'string' } }, confidence: { type: 'number', minimum: 0, maximum: 1 } } }, parse(v) { if (!isObj(v)) throw new Error('CoachResponse object'); return { message: str(v.message, 'message'), safety_disclaimer: typeof v.safety_disclaimer === 'string' ? v.safety_disclaimer : undefined, suggested_actions: strArr(v.suggested_actions, 'suggested_actions'), tool_results_used: strArr(v.tool_results_used, 'tool_results_used'), confidence: num(v.confidence, 'confidence', 0, 1) }; } };
export const InsightResponseSchema: Schema<InsightResponse> = { name: 'InsightResponse', jsonSchema: { type: 'object', required: ['type','title','body','supporting_facts','confidence'], properties: { type: { enum: ['nutrition','progress','goal','general'] }, title: { type: 'string' }, body: { type: 'string' }, supporting_facts: { type: 'array', items: { type: 'string' } }, confidence: { type: 'number', minimum: 0, maximum: 1 }, valid_until: { type: ['string','null'] } } }, parse(v) { if (!isObj(v)) throw new Error('InsightResponse object'); const type = str(v.type, 'type') as InsightResponse['type']; if (!['nutrition','progress','goal','general'].includes(type)) throw new Error('invalid insight type'); return { type, title: str(v.title, 'title'), body: str(v.body, 'body'), supporting_facts: strArr(v.supporting_facts, 'supporting_facts'), confidence: num(v.confidence, 'confidence', 0, 1), valid_until: typeof v.valid_until === 'string' || v.valid_until === null ? v.valid_until : undefined }; } };
export const RecommendationResponseSchema: Schema<RecommendationResponse> = { name: 'RecommendationResponse', jsonSchema: { type: 'object', required: ['recommendations','confidence'], properties: { recommendations: { type: 'array' }, confidence: { type: 'number', minimum: 0, maximum: 1 } } }, parse(v) { if (!isObj(v)) throw new Error('RecommendationResponse object'); return { recommendations: arr(v.recommendations, 'recommendations', (x, i) => { if (!isObj(x)) throw new Error(`recommendations[${i}] object`); const recommendation_type = str(x.recommendation_type, 'recommendation_type') as RecommendationResponse['recommendations'][number]['recommendation_type']; if (!['group','live_room','habit','coach'].includes(recommendation_type)) throw new Error('invalid recommendation_type'); return { recommendation_type, target_id: typeof x.target_id === 'string' || x.target_id === null ? x.target_id : undefined, title: str(x.title, 'title'), reason: str(x.reason, 'reason'), score: num(x.score, 'score', 0, 1) }; }), confidence: num(v.confidence, 'confidence', 0, 1) }; } };
export function parseStructured<T>(schema: Schema<T>, raw: string): T { try { return schema.parse(JSON.parse(raw)); } catch (e) { throw new GatewayError('STRUCTURED_OUTPUT_INVALID', e instanceof Error ? e.message : 'Invalid structured output', 502); } }
export function responseFormat(schema: Schema<unknown>) { return { type: 'json_schema', json_schema: { name: schema.name, strict: true, schema: schema.jsonSchema } }; }
