// @ts-nocheck
import { GatewayError, type ToolContext, type ToolDefinition } from './types.ts';
import { getActiveGoal, getNutritionHistory, getRecentFoodLogs, getUserProfile, getWeightTrend } from './context.ts';
export const TOOL_SCHEMA_VERSION = '2026-08';
type Handler = (args: Record<string, unknown>, ctx: ToolContext) => Promise<unknown>;
type ToolSpec = { name: string; description: string; parameters: Record<string, unknown>; handler: Handler };
const objectSchema = (properties: Record<string, unknown> = {}, required: string[] = []) => ({ type: 'object', additionalProperties: false, properties, required });
function assertCallerScope(args: Record<string, unknown>, ctx: ToolContext) { if (typeof args.user_id === 'string' && args.user_id !== ctx.userId) throw new GatewayError('TOOL_NOT_ALLOWED', 'Tool arguments may not target another user.', 403); if (typeof args.userId === 'string' && args.userId !== ctx.userId) throw new GatewayError('TOOL_NOT_ALLOWED', 'Tool arguments may not target another user.', 403); }
const unavailable = (table: string): Handler => async (args, ctx) => { assertCallerScope(args, ctx); return { error: { code: 'NOT_YET_AVAILABLE', message: `Requires application logic/table: ${table}` } }; };
const tools: ToolSpec[] = [
  { name: 'get_user_profile', description: 'Read caller profile summary.', parameters: objectSchema(), handler: async (a, c) => { assertCallerScope(a,c); return await getUserProfile(c.supabase, c.userId); } },
  { name: 'get_user_goals', description: 'Read caller goals.', parameters: objectSchema(), handler: async (a, c) => { assertCallerScope(a,c); const r = await c.supabase.from('goals').select('id,title,type,status,target_value,unit,target_date').eq('user_id', c.userId).limit(10); if (r?.error) throw new Error(r.error.message); return r?.data ?? []; } },
  { name: 'get_active_goal', description: 'Read caller active goal.', parameters: objectSchema(), handler: async (a, c) => { assertCallerScope(a,c); return await getActiveGoal(c.supabase, c.userId); } },
  { name: 'get_goal', description: 'Alias for get_active_goal.', parameters: objectSchema(), handler: async (a, c) => { assertCallerScope(a,c); return await getActiveGoal(c.supabase, c.userId); } },
  { name: 'get_today_nutrition', description: 'Read caller deterministic nutrition summary for today.', parameters: objectSchema({ date: { type: 'string' } }), handler: async (a, c) => { assertCallerScope(a,c); const date = typeof a.date === 'string' ? a.date : new Date().toISOString().slice(0,10); return await c.supabase.from('daily_nutrition_summaries').select('date,calories,protein_g,carbs_g,fat_g,fiber_g,water_ml,meal_count').eq('user_id', c.userId).eq('date', date).maybeSingle(); } },
  { name: 'get_daily_nutrition', description: 'Read caller deterministic daily nutrition.', parameters: objectSchema({ date: { type: 'string' } }), handler: async (a, c) => { assertCallerScope(a,c); const date = typeof a.date === 'string' ? a.date : new Date().toISOString().slice(0,10); return await c.supabase.from('daily_nutrition_summaries').select('*').eq('user_id', c.userId).eq('date', date).maybeSingle(); } },
  { name: 'get_nutrition_history', description: 'Read caller nutrition history.', parameters: objectSchema({ days: { type: 'number', minimum: 1, maximum: 90 } }), handler: async (a, c) => { assertCallerScope(a,c); return await getNutritionHistory(c.supabase, c.userId, Math.min(Number(a.days ?? 7), 90)); } },
  { name: 'get_weight_history', description: 'Read caller weight history.', parameters: objectSchema({ days: { type: 'number' } }), handler: async (a, c) => { assertCallerScope(a,c); return await getWeightTrend(c.supabase, c.userId, Math.min(Number(a.days ?? 30), 365)); } },
  { name: 'get_weight_trend', description: 'Read caller recent weight trend.', parameters: objectSchema({ days: { type: 'number' } }), handler: async (a, c) => { assertCallerScope(a,c); return await getWeightTrend(c.supabase, c.userId, Math.min(Number(a.days ?? 30), 365)); } },
  { name: 'get_food_log', description: 'Read caller recent food logs.', parameters: objectSchema({ days: { type: 'number' } }), handler: async (a, c) => { assertCallerScope(a,c); return await getRecentFoodLogs(c.supabase, c.userId, Math.min(Number(a.days ?? 7), 30)); } },
  { name: 'get_recent_food_logs', description: 'Read caller recent food logs.', parameters: objectSchema({ days: { type: 'number' } }), handler: async (a, c) => { assertCallerScope(a,c); return await getRecentFoodLogs(c.supabase, c.userId, Math.min(Number(a.days ?? 7), 30)); } },
  { name: 'search_foods', description: 'Search canonical foods.', parameters: objectSchema({ query: { type: 'string' } }, ['query']), handler: async (a, c) => { assertCallerScope(a,c); const r = await c.supabase.from('foods').select('id,name,brand,source,serving_size,serving_unit').limit(25); if (r?.error) throw new Error(r.error.message); const q = String(a.query ?? '').toLowerCase(); return (r?.data ?? []).filter((f) => String(f.name).toLowerCase().includes(q)); } },
  ...['get_measurements','get_progress_summary','get_activity_summary','get_user_groups','get_recommended_groups','get_live_rooms','get_upcoming_sessions','get_coach_relationship','create_food_log','update_food_log','delete_food_log','create_goal','update_goal','create_progress_entry','recommend_group','recommend_live_room'].map((name) => ({ name, description: `${name} (caller-scoped allowlisted Veralify tool)`, parameters: objectSchema(), handler: unavailable(name) }))
];
export const toolRegistry = new Map(tools.map((t) => [t.name, t]));
export function getOpenRouterTools(namesToUse?: string[]): ToolDefinition[] { const selected = namesToUse ? namesToUse.map((n) => { const t = toolRegistry.get(n); if (!t) throw new GatewayError('TOOL_NOT_ALLOWED', `Tool ${n} is not allowlisted`, 400); return t; }) : tools; return selected.map((t) => ({ type: 'function', function: { name: t.name, description: t.description, parameters: t.parameters } })); }
export async function executeTool(name: string, args: Record<string, unknown>, ctx: ToolContext): Promise<unknown> { const tool = toolRegistry.get(name); if (!tool) throw new GatewayError('TOOL_NOT_ALLOWED', `Tool ${name} is not allowlisted`, 400); const result = await tool.handler(args ?? {}, ctx); return result?.data !== undefined && result?.error !== undefined ? (result.error ? { error: result.error } : result.data) : result; }
