// @ts-nocheck
import { GatewayError, type ToolContext, type ToolDefinition } from './types.ts';
import { getActiveGoal, getNutritionHistory, getRecentFoodLogs, getUserProfile, getWeightTrend } from './context.ts';
export const TOOL_SCHEMA_VERSION = '2026-08';
type Handler = (args: Record<string, unknown>, ctx: ToolContext) => Promise<unknown>;
type ToolSpec = { name: string; description: string; parameters: Record<string, unknown>; handler: Handler; status: 'real' | 'not_yet_available' };
const objectSchema = (properties: Record<string, unknown> = {}, required: string[] = []) => ({ type: 'object', additionalProperties: false, properties, required });
function assertCallerScope(args: Record<string, unknown>, ctx: ToolContext) { if (typeof args.user_id === 'string' && args.user_id !== ctx.userId) throw new GatewayError('TOOL_NOT_ALLOWED', 'Tool arguments may not target another user.', 403); if (typeof args.userId === 'string' && args.userId !== ctx.userId) throw new GatewayError('TOOL_NOT_ALLOWED', 'Tool arguments may not target another user.', 403); }
const unavailable = (table: string): Handler => async (args, ctx) => { assertCallerScope(args, ctx); return { error: { code: 'NOT_YET_AVAILABLE', message: `Requires application logic/table: ${table}` } }; };
const qdata = async (q: unknown) => { const r = await q; if (r?.error) throw new Error(r.error.message); return r?.data ?? []; };
const real = (name: string, description: string, parameters: Record<string, unknown>, handler: Handler): ToolSpec => ({ name, description, parameters, handler, status: 'real' });
const blocked = (name: string): ToolSpec => ({ name, description: `${name} (caller-scoped allowlisted Veralify tool)`, parameters: objectSchema(), handler: unavailable(name), status: 'not_yet_available' });
const tools: ToolSpec[] = [
  real('get_user_profile', 'Read caller profile summary.', objectSchema(), async (a, c) => { assertCallerScope(a,c); return await getUserProfile(c.supabase, c.userId); }),
  real('get_user_goals', 'Read caller goals.', objectSchema(), async (a, c) => { assertCallerScope(a,c); return await qdata(c.supabase.from('goals').select('id,title,type,status,target_value,unit,target_date,updated_at').eq('user_id', c.userId).limit(10)); }),
  real('get_active_goal', 'Read caller active goal.', objectSchema(), async (a, c) => { assertCallerScope(a,c); return await getActiveGoal(c.supabase, c.userId); }),
  real('get_goal', 'Alias for get_active_goal.', objectSchema(), async (a, c) => { assertCallerScope(a,c); return await getActiveGoal(c.supabase, c.userId); }),
  real('get_today_nutrition', 'Read caller deterministic nutrition summary for today.', objectSchema({ date: { type: 'string' } }), async (a, c) => { assertCallerScope(a,c); const date = typeof a.date === 'string' ? a.date : new Date().toISOString().slice(0,10); const r = await c.supabase.from('daily_nutrition_summaries').select('date,calories,protein_g,carbs_g,fat_g,fiber_g,water_ml,meal_count').eq('user_id', c.userId).eq('date', date).maybeSingle(); if (r?.error) throw new Error(r.error.message); return r?.data ?? null; }),
  real('get_daily_nutrition', 'Read caller deterministic daily nutrition.', objectSchema({ date: { type: 'string' } }), async (a, c) => { assertCallerScope(a,c); const date = typeof a.date === 'string' ? a.date : new Date().toISOString().slice(0,10); const r = await c.supabase.from('daily_nutrition_summaries').select('*').eq('user_id', c.userId).eq('date', date).maybeSingle(); if (r?.error) throw new Error(r.error.message); return r?.data ?? null; }),
  real('get_nutrition_history', 'Read caller nutrition history.', objectSchema({ days: { type: 'number', minimum: 1, maximum: 90 } }), async (a, c) => { assertCallerScope(a,c); return await getNutritionHistory(c.supabase, c.userId, Math.min(Number(a.days ?? 7), 90)); }),
  real('get_weight_history', 'Read caller weight history.', objectSchema({ days: { type: 'number' } }), async (a, c) => { assertCallerScope(a,c); return await getWeightTrend(c.supabase, c.userId, Math.min(Number(a.days ?? 30), 365)); }),
  real('get_weight_trend', 'Read caller recent weight trend.', objectSchema({ days: { type: 'number' } }), async (a, c) => { assertCallerScope(a,c); return await getWeightTrend(c.supabase, c.userId, Math.min(Number(a.days ?? 30), 365)); }),
  real('get_food_log', 'Read caller recent food logs.', objectSchema({ days: { type: 'number' } }), async (a, c) => { assertCallerScope(a,c); return await getRecentFoodLogs(c.supabase, c.userId, Math.min(Number(a.days ?? 7), 30)); }),
  real('get_recent_food_logs', 'Read caller recent food logs.', objectSchema({ days: { type: 'number' } }), async (a, c) => { assertCallerScope(a,c); return await getRecentFoodLogs(c.supabase, c.userId, Math.min(Number(a.days ?? 7), 30)); }),
  real('get_measurements', 'Read caller body measurements.', objectSchema({ days: { type: 'number' } }), async (a, c) => { assertCallerScope(a,c); const days = Math.min(Number(a.days ?? 90), 365); const since = new Date(Date.now() - days * 86400_000).toISOString(); return await qdata(c.supabase.from('body_measurements').select('measured_at,measurement_type,value,unit').eq('user_id', c.userId).gte('measured_at', since).order('measured_at', { ascending: false }).limit(50)); }),
  real('get_user_groups', 'Read active groups for caller.', objectSchema(), async (a, c) => { assertCallerScope(a,c); const memberships = await qdata(c.supabase.from('group_members').select('group_id,role,status,joined_at').eq('user_id', c.userId).eq('status', 'active').limit(50)); const ids = memberships.map((m) => m.group_id).filter(Boolean); if (!ids.length) return []; const groups = await qdata(c.supabase.from('groups').select('id,name,slug,goal_type,type,visibility,is_active').in('id', ids).eq('is_active', true).limit(50)); return groups.map((g) => ({ ...g, membership: memberships.find((m) => m.group_id === g.id) })); }),
  real('get_recent_posts', 'Read recent posts from caller joined groups.', objectSchema({ limit: { type: 'number' } }), async (a, c) => { assertCallerScope(a,c); const memberships = await qdata(c.supabase.from('group_members').select('group_id').eq('user_id', c.userId).eq('status', 'active').limit(50)); const ids = memberships.map((m) => m.group_id).filter(Boolean); if (!ids.length) return []; return await qdata(c.supabase.from('posts').select('id,group_id,author_id,content,post_type,visibility,created_at').in('group_id', ids).eq('status', 'published').order('created_at', { ascending: false }).limit(Math.min(Number(a.limit ?? 10), 25))); }),
  real('get_upcoming_sessions', 'Read caller booked upcoming coaching sessions.', objectSchema({ limit: { type: 'number' } }), async (a, c) => { assertCallerScope(a,c); const bookings = await qdata(c.supabase.from('session_bookings').select('id,session_id,status,booked_at').eq('client_id', c.userId).eq('status', 'confirmed').limit(Math.min(Number(a.limit ?? 10), 25))); const ids = bookings.map((b) => b.session_id).filter(Boolean); if (!ids.length) return []; const now = new Date().toISOString(); const sessions = await qdata(c.supabase.from('coach_sessions').select('id,title,scheduled_at,duration_minutes,session_type,status,coach_id').in('id', ids).gte('scheduled_at', now).order('scheduled_at', { ascending: true }).limit(ids.length)); return sessions.map((s) => ({ ...s, booking: bookings.find((b) => b.session_id === s.id) })); }),
  real('search_foods', 'Search canonical foods.', objectSchema({ query: { type: 'string' } }, ['query']), async (a, c) => { assertCallerScope(a,c); const r = await c.supabase.from('foods').select('id,name,brand,source,serving_size,serving_unit').limit(100); if (r?.error) throw new Error(r.error.message); const q = String(a.query ?? '').toLowerCase(); return (r?.data ?? []).filter((f) => String(f.name).toLowerCase().includes(q)).slice(0,25); }),
  ...['get_progress_summary','get_activity_summary','get_recommended_groups','get_live_rooms','get_coach_relationship','create_food_log','update_food_log','delete_food_log','create_goal','update_goal','create_progress_entry','recommend_group','recommend_live_room'].map(blocked)
];
export const toolRegistry = new Map(tools.map((t) => [t.name, t]));
export const toolStatus = Object.fromEntries(tools.map((t) => [t.name, t.status]));
export function getOpenRouterTools(namesToUse?: string[]): ToolDefinition[] { const selected = namesToUse ? namesToUse.map((n) => { const t = toolRegistry.get(n); if (!t) throw new GatewayError('TOOL_NOT_ALLOWED', `Tool ${n} is not allowlisted`, 400); return t; }) : tools; return selected.map((t) => ({ type: 'function', function: { name: t.name, description: t.description, parameters: t.parameters } })); }
export async function executeTool(name: string, args: Record<string, unknown>, ctx: ToolContext): Promise<unknown> { const tool = toolRegistry.get(name); if (!tool) throw new GatewayError('TOOL_NOT_ALLOWED', `Tool ${name} is not allowlisted`, 400); return await tool.handler(args ?? {}, ctx); }
